jobs:
- name: build
  plan:
    - get: gpupgrade_src
      trigger: true
    - task: build
      config:
        platform: linux
        image_resource:
          type: registry-image
          source:
            repository: gcr.io/data-gpdb-public-images/gpdb6-centos7-test-golang
            tag: latest
        inputs:
          - name: gpupgrade_src
        outputs:
          - name: built_enterprise
        params:
                GIT_SSH_KEY: ((server/gpdb-deploy-key))
        run:
          path: gpupgrade_src/ci/main/scripts/build.bash
    - put: enterprise_rpm
      params:
        file: built_enterprise/gpupgrade-*.rpm

- name: lint
  plan:
    - get: gpupgrade_src
      trigger: true
    - task: lint
      config:
        platform: linux
        image_resource:
          type: registry-image
          source:
            repository: golangci/golangci-lint
        inputs:
          - name: gpupgrade_src
        run:
          path: bash
          args:
            - -c
            - |
              set -eux -o pipefail

              cd gpupgrade_src
              make lint
